-- ================================================
-- Muestrame el perro que tenga mas ultimos puestos
-- FUTURO PROBLEMA
-- ===============================================}
Mostrar la cantidad de veces que a participado un perro en un concurso en especifico
Mostrar lista de los concursantes y que muestre la cantidad de veces el perro a llegado a ganar hasta la fecha del concurso que se especificara

mOSTARR UN PRECIO ESPECIAL PARA LO CANES QUE SON REITERATIVOS Y NO LLEGARON A SER DEL PODIO


- Muestrame el perro que tenga mas participaciones
- Mostrar la raza de perros que mas a concursado

-- SP: REGISTRO DE UN PERRO TOTAL A UN CONCURSO, que reciba todos los parametros posibles para validrlo con todas las tablas
--      SELE PASA LA EDAD Y TE MUESTRA EL CONCURSO QUE SERIA IDEAL CON EL PRECIO